<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>IOT Monitoring Kit Configuration</title>
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link href="css/mchp-min.css" rel="stylesheet" type="text/css">
	<script src="javascript/mchp.js" type="text/javascript"></script>
</head>
	<body>
	<div id="page">
		<div id="content">
			<div class="logo">
				<div>
					<img src="images/m1.png" alt="Medium One">
				</div>
			</div>

